# Generated by Django 3.0.3 on 2020-02-19 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('ticker_full_name', models.CharField(default='', max_length=100)),
                ('function', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=10)),
                ('series_type', models.CharField(default='close', max_length=10)),
                ('days_to_store', models.IntegerField()),
                ('low_freq_period', models.IntegerField()),
                ('high_freq_period', models.IntegerField()),
                ('low_streak_alert', models.IntegerField()),
                ('high_streak_alert', models.IntegerField()),
                ('latest_low_price', models.FloatField(default=0)),
                ('latest_high_price', models.FloatField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('status_duration', models.IntegerField()),
                ('prev_status', models.CharField(max_length=10, null=True)),
                ('holiday', models.BooleanField()),
                ('most_recent_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Fund')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fundprices',
            constraint=models.UniqueConstraint(fields=('fund', 'freq_type', 'date'), name='no_repeated_dates'),
        ),
    ]
