# Generated by Django 3.0.2 on 2020-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='prev_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
