# Generated by Django 3.0.2 on 2020-01-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200112_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='latest_high_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='latest_low_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='ticker_full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
