# Generated by Django 3.0.2 on 2020-01-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200112_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='most_recent_date',
            field=models.DateField(null=True),
        ),
    ]
